# Generated by Django 2.2.1 on 2019-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190605_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Add the names of the author(s)', max_length=200, to='catalog.Author'),
        ),
    ]
