# Generated by Django 2.2.1 on 2019-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190611_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Enter the language(s) here', max_length=100, related_name='books', to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(help_text='Select a subject for this book', related_name='books', to='catalog.Subject'),
        ),
    ]
